config/routes.rb
ExpirySyncServer::Application.routes.draw do
  resources :alternate_servers

  resources :article_images

  resources :producers

  devise_for :users, controllers: {sessions: "sessions", registrations: "registrations", passwords: "passwords"}

  resources :articles
  get 'articles/by_barcode/:barcode' => 'articles#by_barcode'

  resources :product_entries, only: [:create, :update, :destroy]

  resources :locations do
    get "index_mine_changed", on: :collection
    resources :location_shares
    resources :product_entries do
      get "index_changed", on: :collection
    end
  end

  resources :article_images do
    get "serve", :on => :member
  end

  get "/pages/:page" => "pages#show"

  root to: 'pages#show', page: 'home'
end

app/models/alternate_server.rb
class AlternateServer < ActiveRecord::Base
  track_who_does_it creator_foreign_key: "creator_id", updater_foreign_key: "modifier_id"
  acts_as_paranoid
  
  translates :name, :description, :replacement_explanation
  globalize_accessors
  
  validates :url, presence: true, uniqueness: true, :format => URI::regexp(%w(http https))
end

app/controllers/alternate_servers_controller.rb
class AlternateServersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  load_resource except: [:index, :new]
  authorize_resource except: [:index, :new, :create]

  respond_to :html

  def index
    @alternate_servers = AlternateServer.all
    respond_to do |format|
      format.html { respond_with(@alternate_servers) }
      format.json { render json: {
        status: 'success', 
        alternate_servers: JSON.parse(@alternate_servers.to_json(include: :creator))
      }}
    end
  end

  def new
    @alternate_server = AlternateServer.new
    respond_with(@alternate_server)
  end

  def edit
  end

  def create
    # strip superflous i18n fields from params:
    clean_params = alternate_server_params.dup
    I18n.available_locales.each do |lang|
      next unless clean_params["name_#{lang}"].empty? and clean_params["description_#{lang}"].empty?
      clean_params.delete("name_#{lang}")
      clean_params.delete("description_#{lang}")
    end
    
    @alternate_server = AlternateServer.new(clean_params)
    if @alternate_server.save
      flash[:notice] = I18n.t(:successfully_created_alternate_server)
    end
    
    respond_with(@alternate_server, location: alternate_servers_path)
  end

  def update
    # strip superflous i18n fields from params:
    clean_params = alternate_server_params.dup
    I18n.available_locales.each do |lang|
      next unless clean_params["name_#{lang}"].empty? and clean_params["description_#{lang}"].empty? \
        and @alternate_server.send("name_#{lang}".to_sym).nil? and @alternate_server.send("description_#{lang}".to_sym).nil? 
      clean_params.delete("name_#{lang}")
      clean_params.delete("description_#{lang}")
    end
    
    clean_params['replacement_url'] = nil if clean_params['replacement_url'] == ''
    @alternate_server.update(clean_params)
    respond_with(@alternate_server, location: alternate_servers_path)
  end

  def destroy
    if @alternate_server.destroy
      flash[:notice] = I18n.t(:successfully_deleted_alternate_server)
    else
      flash[:notice] = I18n.t(:error_deleting_alternate_server)
    end
    respond_with(@alternate_server, location: alternate_servers_path)
  end

  private
    def alternate_server_params
      fields_arr = [:url, :replacement_url]
      
      I18n.available_locales.each do |lang|
        fields_arr << "name_#{lang}".to_sym
        fields_arr << "description_#{lang}".to_sym
        fields_arr << "replacement_explanation_#{lang}".to_sym
      end
      
      params.require(:alternate_server).permit(fields_arr)
    end
end

app/helpers/alternate_servers_helper.rb
module AlternateServersHelper
end

app/views/alternate_servers/_form.html.haml
= form_for(@alternate_server) do |f|
  - if @alternate_server.errors.any?
    #error_explanation
      %h2
        = t(:error_prohibited_saving, count: @alternate_server.errors.count)
        \:
      %ul
        - @alternate_server.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :replacement_url
    = f.text_field :replacement_url
  - I18n.available_locales.each do |lang|
    .field{"data-lang" => lang}
      = f.label(AlternateServer.human_attribute_name("name") + " (#{lang})", for: "alternate_server_name_#{lang}")
      %br/
      = f.text_field "name_#{lang}"
    .field{"data-lang" => lang}
      = f.label(AlternateServer.human_attribute_name("description") + " (#{lang})", for: "alternate_server_description_#{lang}")
      %br/
      = f.text_area "description_#{lang}"
    .field{"data-lang" => lang}
      = f.label(AlternateServer.human_attribute_name("replacement_explanation") + " (#{lang})", for: "replacement_explanation_#{lang}")
      %br/
      = f.text_area "replacement_explanation_#{lang}"
  .actions
    = f.submit

app/views/alternate_servers/edit.html.haml
- content_for :head do
  %meta{name: 'robots', content: 'noindex, nofollow'}
%h1= t(:editing_alternate_server)
= render 'form'
= link_to 'Back', alternate_servers_path

app/views/alternate_servers/index.html.haml
- content_for :head do
  %meta{name: 'robots', content: 'noindex, nofollow'}
%h1= AlternateServer.model_name.human(count: 3)
%table
  %thead
    %tr
      %th= AlternateServer.human_attribute_name(:name)
      %th= AlternateServer.human_attribute_name(:url)
      %th= AlternateServer.human_attribute_name(:description)
      %th= t(:added_by)
      %th= AlternateServer.human_attribute_name(:updated_at)
      %th 
      %th.actions
  %tbody
    - @alternate_servers.each do |alternate_server|
      %tr
        %td= alternate_server.name
        %td= alternate_server.url
        %td= alternate_server.description
        %td.user= alternate_server.creator
        %td.datetime= l(alternate_server.updated_at, format: :short)
        %td.actions
          - if can? :update, alternate_server
            = link_to t(:edit), edit_alternate_server_path(alternate_server)
          - if can? :destroy, alternate_server
            = link_to t(:delete), alternate_server, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to(t(:new_alternate_server), new_alternate_server_path, class: 'block_link')

app/views/alternate_servers/new.html.haml
%h1= t(:new_alternate_server)
= render 'form'
= link_to 'Back', alternate_servers_path